springboot-oshi/src/main/java/com/daryl/oshi/domain/Cpu.java
package com.daryl.oshi.domain;

import com.daryl.oshi.util.ArithUtils;
import lombok.Setter;

/**
 * CPU相关信息
 *
 * @author daryl
 * @date 2019/1/30 16:00
 */
@Setter
public class Cpu {
    /**
     * 核心数
     */
    private int cpuNum;

    /**
     * CPU总的使用率
     */
    private double total;

    /**
     * CPU系统使用率
     */
    private double sys;

    /**
     * CPU用户使用率
     */
    private double used;

    /**
     * CPU当前等待率
     */
    private double wait;

    /**
     * CPU当前空闲率
     */
    private double free;

    public int getCpuNum() {
        return cpuNum;
    }


    public double getTotal() {
        return ArithUtils.round(ArithUtils.mul(total, 100), 2);
    }


    public double getSys() {
        return ArithUtils.round(ArithUtils.mul(sys / total, 100), 2);
    }


    public double getUsed() {
        return ArithUtils.round(ArithUtils.mul(used / total, 100), 2);
    }


    public double getWait() {
        return ArithUtils.round(ArithUtils.mul(wait / total, 100), 2);
    }


    public double getFree() {
        return ArithUtils.round(ArithUtils.mul(free / total, 100), 2);
    }

}

springboot-oshi/src/main/java/com/daryl/oshi/domain/Jvm.java
package com.daryl.oshi.domain;

import com.daryl.oshi.util.ArithUtils;
import com.daryl.oshi.util.DateUtils;
import lombok.Setter;

import java.lang.management.ManagementFactory;

/**
 * JVM相关信息
 *
 * @author daryl
 * @date 2019/1/30 16:00
 */
@Setter
public class Jvm {
    /**
     * 当前JVM占用的内存总数(M)
     */
    private double total;

    /**
     * JVM最大可用内存总数(M)
     */
    private double max;

    /**
     * JVM空闲内存(M)
     */
    private double free;

    /**
     * JDK版本
     */
    private String version;

    /**
     * JDK路径
     */
    private String home;

    public double getTotal() {
        return ArithUtils.div(total, (1024 * 1024), 2);
    }

    public double getMax() {
        return ArithUtils.div(max, (1024 * 1024), 2);
    }

    public double getFree() {
        return ArithUtils.div(free, (1024 * 1024), 2);
    }

    public String getVersion() {
        return version;
    }

    public String getHome() {
        return home;
    }

    public double getUsed() {
        return ArithUtils.div(total - free, (1024 * 1024), 2);
    }

    public double getUsage() {
        return ArithUtils.mul(ArithUtils.div(total - free, total, 4), 100);
    }

    /**
     * 获取JDK名称
     */
    public String getName() {
        return ManagementFactory.getRuntimeMXBean().getVmName();
    }

    /**
     * JDK启动时间
     */
    public String getStartTime() {
        return DateUtils.parseDateToStr(DateUtils.YYYY_MM_DD_HH_MM_SS, DateUtils.getServerStartDate());
    }

    /**
     * JDK运行时间
     */
    public String getRunTime() {
        return DateUtils.getDatePoor(DateUtils.getNowDate(), DateUtils.getServerStartDate());
    }
}

springboot-oshi/src/main/java/com/daryl/oshi/domain/Mem.java
package com.daryl.oshi.domain;

import com.daryl.oshi.util.ArithUtils;
import lombok.Setter;

/**
 * 內存相关信息
 *
 * @author daryl
 * @date 2019/1/30 16:00
 */
@Setter
public class Mem {
    /**
     * 内存总量
     */
    private double total;

    /**
     * 已用内存
     */
    private double used;

    /**
     * 剩余内存
     */
    private double free;

    public double getTotal() {
        return ArithUtils.div(total, (1024 * 1024 * 1024), 2);
    }

    public double getUsed() {
        return ArithUtils.div(used, (1024 * 1024 * 1024), 2);
    }

    public double getFree() {
        return ArithUtils.div(free, (1024 * 1024 * 1024), 2);
    }

    public double getUsage() {
        return ArithUtils.mul(ArithUtils.div(used, total, 4), 100);
    }
}

springboot-oshi/src/main/java/com/daryl/oshi/domain/Sys.java
package com.daryl.oshi.domain;

import lombok.Data;

/**
 * 系统相关信息
 *
 * @author daryl
 * @date 2019/1/30 16:00
 */
@Data
public class Sys {
    /**
     * 服务器名称
     */
    private String computerName;

    /**
     * 服务器Ip
     */
    private String computerIp;

    /**
     * 项目路径
     */
    private String userDir;

    /**
     * 操作系统
     */
    private String osName;

    /**
     * 系统架构
     */
    private String osArch;

}

springboot-oshi/src/main/java/com/daryl/oshi/domain/SysFile.java
package com.daryl.oshi.domain;

import lombok.Data;

/**
 * 系统文件相关信息
 *
 * @author daryl
 * @date 2019/1/30 16:00
 */
@Data
public class SysFile {
    /**
     * 盘符路径
     */
    private String dirName;

    /**
     * 盘符类型
     */
    private String sysTypeName;

    /**
     * 文件类型
     */
    private String typeName;

    /**
     * 总大小
     */
    private String total;

    /**
     * 剩余大小
     */
    private String free;

    /**
     * 已经使用量
     */
    private String used;

    /**
     * 资源的使用率
     */
    private double usage;

}

springboot-oshi/src/main/java/com/daryl/oshi/controller/ServerController.java
package com.daryl.oshi.controller;

import com.daryl.oshi.config.ServerConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * 服务器监控
 *
 * @author daryl
 * @date 2019/1/30 17:40
 */
@Controller
@RequestMapping("/")
public class ServerController {

    private static final Logger logger = LoggerFactory.getLogger(ServerController.class);

    private String prefix = "monitor/server/";

    @RequestMapping("/")
    public String server(ModelMap map) throws Exception {
        ServerConfig serverConfig = new ServerConfig();
        serverConfig.copyTo();
        map.put("server", serverConfig);
        logger.info("server------");
        return prefix + "server";
    }

}

springboot-oshi/src/main/resources/templates/monitor/server/server.ftl
<!DOCTYPE html>
<html lang="zh" xmlns:th="http://www.thymeleaf.org"
      xmlns:shiro="http://www.pollix.at/thymeleaf/shiro">
<meta charset="utf-8">
<head th:include="include :: header"></head>
<body class="gray-bg" id="test">
<div class="wrapper wrapper-content">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>CPU</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <table class="table table-hover no-margins">
                            <thead>
                            <tr>
                                <th>属性</th>
                                <th>值</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>核心数</td>
                                <td th:text="${server.cpu.cpuNum}">0个</td>
                            </tr>
                            <tr>
                                <td>用户使用率</td>
                                <td th:text="${server.cpu.used + '%'}">0%</td>
                            </tr>
                            <tr>
                                <td>系统使用率</td>
                                <td th:text="${server.cpu.sys + '%'}">0%</td>
                            </tr>
                            <tr>
                                <td>当前空闲率</td>
                                <td th:text="${server.cpu.free + '%'}">0%</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>内存</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            <a class="close-link"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <table class="table table-hover no-margins">
                            <thead>
                            <tr>
                                <th>属性</th>
                                <th>内存</th>
                                <th>JVM</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>总内存</td>
                                <td th:text="${server.mem.total + 'G'}">0GB</td>
                                <td th:text="${server.jvm.total + 'M'}">0MB</td>
                            </tr>
                            <tr>
                                <td>已用内存</td>
                                <td th:text="${server.mem.used + 'G'}">0GB</td>
                                <td th:text="${server.jvm.used + 'M'}">0MB</td>
                            </tr>
                            <tr>
                                <td>剩余内存</td>
                                <td th:text="${server.mem.free + 'G'}">0GB</td>
                                <td th:text="${server.jvm.free + 'M'}">0MB</td>
                            </tr>
                            <tr>
                                <td>使用率</td>
                                <td th:class="${server.mem.usage gt 80} ? 'text-danger'">[[${server.mem.usage}]]%</td>
                                <td th:class="${server.jvm.usage gt 80} ? 'text-danger'">[[${server.jvm.usage}]]%</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>服务器信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover margin bottom">
                                    <tbody>
                                    <tr>
                                        <td>服务器名称</td>
                                        <td th:text="${server.sys.computerName}">RuoYi</td>
                                        <td>操作系统</td>
                                        <td th:text="${server.sys.osName}">Linux</td>
                                    </tr>
                                    <tr>
                                        <td>服务器IP</td>
                                        <td th:text="${server.sys.computerIp}">127.0.0.1</td>
                                        <td>系统架构</td>
                                        <td th:text="${server.sys.osArch}">amd64</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Java虚拟机信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover margin bottom">
                                    <tbody>
                                    <tr>
                                        <td>Java名称</td>
                                        <td th:text="${server.jvm.name}">Java</td>
                                        <td>Java版本</td>
                                        <td th:text="${server.jvm.version}">1.8.0</td>
                                    </tr>
                                    <tr>
                                        <td>启动时间</td>
                                        <td th:text="${server.jvm.startTime}">2018-12-31 00:00:00</td>
                                        <td>运行时长</td>
                                        <td th:text="${server.jvm.runTime}">0天0时0分0秒</td>
                                    </tr>
                                    <tr>
                                        <td colspan="1">安装路径</td>
                                        <td colspan="3" th:text="${server.jvm.home}"></td>
                                    </tr>
                                    <tr>
                                        <td colspan="1">项目路径</td>
                                        <td colspan="3" th:text="${server.sys.userDir}"></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>磁盘状态</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover margin bottom">
                                    <thead>
                                    <tr>
                                        <th>盘符路径</th>
                                        <th>文件系统</th>
                                        <th>盘符类型</th>
                                        <th>总大小</th>
                                        <th>可用大小</th>
                                        <th>已用大小</th>
                                        <th>已用百分比</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr th:each="sysFile : ${server.sysFiles}">
                                        <td th:text="${sysFile.dirName}">C:\</td>
                                        <td th:text="${sysFile.sysTypeName}">NTFS</td>
                                        <td th:text="${sysFile.typeName}">local</td>
                                        <td th:text="${sysFile.total}">0GB</td>
                                        <td th:text="${sysFile.free}">0GB</td>
                                        <td th:text="${sysFile.used}">0GB</td>
                                        <td th:class="${sysFile.usage gt 80} ? 'text-danger'">[[${sysFile.usage}]]%</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
<div th:include="include :: footer"></div>
<script>
    $(".modal").appendTo("body"), $("[data-toggle=popover]").popover(), $(".collapse-link").click(function () {
        var div_ibox = $(this).closest("div.ibox"),
            e = $(this).find("i"),
            i = div_ibox.find("div.ibox-content");
        i.slideToggle(200),
            e.toggleClass("fa-chevron-up").toggleClass("fa-chevron-down"),
            div_ibox.toggleClass("").toggleClass("border-bottom"),
            setTimeout(function () {
                div_ibox.resize();
            }, 50);
    }), $(".close-link").click(function () {
        var div_ibox = $(this).closest("div.ibox");
        div_ibox.remove()
    });
</script>
</html>